from app.application.common.exceptions.user import UserAlreadyExistsError