from src.application.common.exceptions.user import UserAlreadyExistsError